### ISSUE TITLE
首页网址错误

### ISSUE THREAD

**Issue by peasoft** [nicholascw/b23.wtf#12]
![image](https://user-images.githubusercontent.com/55051861/182115840-6c6488bb-b69f-4e96-83c6-37ed1a6838fb.png)
如图所示，`b23.wtf` 写成了 `b23.tf`

**Comment by nicholascw** [comment]
expected.

**Comment by pzhlkj6612** [comment]
b23.tf is here:

https://github.com/nicholascw/b23.wtf/blob/48bc3be74332e41d3d770a69b4b8551d6820149d/README.md?plain=1#L8
