### ISSUE TITLE
Is it possible to redirect directly to bilibili.com instead of a b23.wtf landing page?

### ISSUE THREAD

**Issue by thekingofcity** [nicholascw/b23.wtf#15]
Is it possible to redirect directly to bilibili.com instead of a b23.wtf landing page? This is the previous behavior of b23.wtf and I really appreciate the work of this project.

**Comment by nicholascw** [comment]
https://github.com/nicholascw/b23.wtf/issues/11#issuecomment-1200438626

Decision is made to notify senders they are sharing their mid= value. If the shared link does not have mid= it will be directly redirected, for example shared through an Google Play version Android Bilibili App.

**Comment by nicholascw** [comment]
Or if there's evidence to prove that base64 version of mid= value is not one-to-one mapped to user's UID and cannot be decrypted by a third-party, it should be fine to lift the landing page feature for those base64-encoded mid URLs.

**Comment by nicholascw** [comment]
Solved by 20e1b9b2da53fdc16ede4d39e84ed445edac1008
